---
- name: Demos for Reuse
  hosts: all
  gather_facts: false
  vars:
    tmpfile_name: testfile

  roles:
    - role: createtmpfile
      vars:
        tmpfile_name: paramtestfile # Achtung: Hier gibt es 2 Wege ...

  tasks:
    - name: debug var
      debug:
        msg: "value of tmpfile_name: /tmp/{{ tmpfile_name }}"
      when: tmpfile_name is defined
    - name: undefined
      debug:
        msg: "tmpfile_name undefined"
      when: tmpfile_name is not defined

  post_tasks:
    - name: rm tmpfile via role
      include_role:
        name: createtmpfile
      vars:
        tmpfile_delete: true
