---
- name: Install Apache
  hosts: training
  become: true
  gather_facts: true
  vars:
    training_apache_packages:
      - apache2
      - apache2-utils
      - apache2-doc

  pre_tasks:
    - name: show variable pre
      debug:
        var: training_apache_packages

  tasks:
    - name: role install apache
      import_role:
        name: roles/setup_apache

#  roles:
#    - setup_apache

  post_tasks:
    - name: show variable post
      debug:
        var: training_apache_packages

- name: Test Apache
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: test apache
      uri:
        url: http://ghilling.training.hilling.de
      register: apache_uri_result
    - name: show variable
      debug:
        var: training_apache_packages
